### ISSUE TITLE
Miner stuck at starting...

### ISSUE THREAD

**Issue by mpizenberg** [nullhashpixel/cltunaminer#3]
When running the cltuna miner, it gets stuck at `starting...`
```
❯ ./cltuna benchmark
CLTUNA OpenCL core v1.0
usage:    ./cltuna [hostname] [port]
examples: ./cltuna
          ./cltuna 0.0.0.0 12345

          ./cltuna benchmark
starting...
```
- OS: Archlinux
- cpu: Intel® Core™ i7-10750H
- gpu: NVIDIA GeForce GTX 1650 Ti + Intel integrated graphics

**Comment by nullhashpixel** [comment]
Please also add the output of "clinfo"

**Comment by mpizenberg** [comment]
![image](https://github.com/nullhashpixel/cltunaminer/assets/2905865/bf8ac10f-9815-4e40-bf5d-2165170ca391)

clinfo stuck in limbo and not answering anything

**Comment by mpizenberg** [comment]
This reddit post seems relevant, I'll see if I can find a solution https://www.reddit.com/r/archlinux/comments/11z79x9/opencl_hangs/

**Comment by mpizenberg** [comment]
Alright so it seems the issue comes from the intel oneapi packages, but I can't just uninstall them as they are dependencies of some other packages I use, such as pytorch or blender. But, according to https://www.reddit.com/r/archlinux/comments/124pgc1/how_to_disable_oneapi_opencl_cpu_backend/ I can remove the file `etc/OpenCL/vendors/intel-oneapi-compiler-shared-opencl-cpu.icd` to disable the oneapi intell stuff.

Sooo, I've just renamed it for now, and now `clinfo` is running normally, and your miner is running normally too :)
The benchmark subcommand gave me hash rate 356672289.436048/s
