### ISSUE TITLE
Unable to connect?

### ISSUE THREAD

**Issue by jafrias2159** [nullhashpixel/cltunaminer#6]
Hello. I followed the readme guide and I got to the point of running both scripts.
But I think the script .cltune is not connecting? (it is been there for a while, no updates)
Any advice? Thanks!
![Screenshot from 2023-09-05 16-56-04](https://github.com/nullhashpixel/cltunaminer/assets/96429774/f8b8f025-a3dd-45dc-94dd-82d47c32d833)

**Comment by nullhashpixel** [comment]
Hi,

it looks like you're using the CPU version of the deno code `deno task cli mine`

For the GPU miner, run `deno task cltunaminer mine`
or
`./run.sh`

**Comment by jafrias2159** [comment]
Awesome, thanks for the help. It worked.
